### ISSUE TITLE
Build issues with nightly-2016-07-07

### ISSUE THREAD

**Issue by freiguy1** [erickt/rust-quasi#56]
Hello there. I'm working on a REST api and am using several libraries like serde, diesel (orm), and iron.  The latest nightly which diesel is able to compile with is `nightly-2016-07-07`. I'm attempting to get this project building and having errors when compiling quasi.

My Cargo.toml file looks like:

``` toml
name = "league-api"
version = "0.0.1"

[dependencies]

# Serialization
serde = "0.8"
serde_json = "0.8"
serde_macros = "0.8"
syntex_syntax = "0.39"

# Iron
iron = "0.4"
persistent = "0.2"
router = "0.2"
bodyparser = "0.4"
hyper = "0.9"

# Data Persistence
diesel = "0.7"
r2d2-diesel = "0.7"
league_db = { path = "../db" }
r2d2 = "0.7"

# Util
regex = "0.1"
pwhash = "0.1"
rand = "0.3"
jwt = "0.4"
rust-crypto = "0.2"
```

My Cargo.lock is quite long, but if needed I can add it.

The error looks like:

```
/home/freied/.multirust/toolchains/nightly-2016-07-07/cargo/registry/src/github.com-1ecc6299db9ec823/quasi-0.16.0/src/lib.rs:230:48: 235:11 error: mismatched types [E0308]
/home/freied/.multirust/toolchains/nightly-2016-07-07/cargo/registry/src/github.com-1ecc6299db9ec823/quasi-0.16.0/src/lib.rs:230         r.push(TokenTree::Delimited(self.span, Rc::new(tokenstream::Delimited {
                                                                                                                                                                                ^
/home/freied/.multirust/toolchains/nightly-2016-07-07/cargo/registry/src/github.com-1ecc6299db9ec823/quasi-0.16.0/src/lib.rs:230:48: 235:11 help: run `rustc --explain E0308` to see a detailed explanation
/home/freied/.multirust/toolchains/nightly-2016-07-07/cargo/registry/src/github.com-1ecc6299db9ec823/quasi-0.16.0/src/lib.rs:230:48: 235:11 note: expected type `syntax::tokenstream::Delimited`
/home/freied/.multirust/toolchains/nightly-2016-07-07/cargo/registry/src/github.com-1ecc6299db9ec823/quasi-0.16.0/src/lib.rs:230:48: 235:11 note:    found type `std::rc::Rc<syntax::tokenstream::Delimited>`
/home/freied/.multirust/toolchains/nightly-2016-07-07/cargo/registry/src/github.com-1ecc6299db9ec823/quasi-0.16.0/src/lib.rs:251:45: 256:11 error: mismatched types [E0308]
/home/freied/.multirust/toolchains/nightly-2016-07-07/cargo/registry/src/github.com-1ecc6299db9ec823/quasi-0.16.0/src/lib.rs:251         vec![TokenTree::Delimited(DUMMY_SP, Rc::new(tokenstream::Delimited {
                                                                                                                                                                             ^
/home/freied/.multirust/toolchains/nightly-2016-07-07/cargo/registry/src/github.com-1ecc6299db9ec823/quasi-0.16.0/src/lib.rs:251:9: 256:13 note: in this expansion of vec! (defined in <std macros>)
/home/freied/.multirust/toolchains/nightly-2016-07-07/cargo/registry/src/github.com-1ecc6299db9ec823/quasi-0.16.0/src/lib.rs:251:45: 256:11 help: run `rustc --explain E0308` to see a detailed explanation
/home/freied/.multirust/toolchains/nightly-2016-07-07/cargo/registry/src/github.com-1ecc6299db9ec823/quasi-0.16.0/src/lib.rs:251:45: 256:11 note: expected type `syntax::tokenstream::Delimited`
/home/freied/.multirust/toolchains/nightly-2016-07-07/cargo/registry/src/github.com-1ecc6299db9ec823/quasi-0.16.0/src/lib.rs:251:45: 256:11 note:    found type `std::rc::Rc<syntax::tokenstream::Delimited>`
error: aborting due to 2 previous errors
Build failed, waiting for other jobs to finish...
error: Could not compile `quasi`.
```

Any ideas?

Thanks!
